### ISSUE TITLE
Error: Unsupported driver [filemaker] Laravel 5.2

### ISSUE THREAD

**Issue by johant** [andrewmile/FMLaravel#3]
Hello,

I'm working on laravel 5.2, and I have the Next Error: Unsupported driver [filemaker], I think that error is in config/app.php, arrays providers.

Which is the provider for Laravel 5.2?

Johan

**Comment by andrewmile** [comment]
Hi Johan,

Make sure you have 'FMLaravel\Database\FileMakerServiceProvider', inside the providers array in config/app.php.  That will register the filemaker database driver.
